#### general settings
name: bsrnn_minx
device: cuda
gpuid: null

#### datasets setings
datasets:
  train_data_dir: /mnt/lustre/sjtu/home/hnz01/code/AILabInTask1/speech-preprocess/data/DatasetTrain80k
  test_data_dir: /mnt/lustre/sjtu/home/hnz01/code/AILabInTask1/speech-preprocess/data/DatasetTest3h
    
#### model settings
model:
  name: BSRNN
  sr: 44100
  win: 2048
  stride: 512
  feature_dim: 80
  num_layer: 6
  num_spk_layer: 4
  same_mask: true

#### training settings: learning rate scheme, loss
train:
  epoch: 100
  batch_size: 1
  early_stop: 10
  sub_batch: 2000
  save_stat_dir: /mnt/lustre/sjtu/home/hnz01/code/AILabInTask1/speech-preprocess/save/x64s_8w/trainstat
  save_model_dir: /mnt/lustre/sjtu/home/hnz01/code/AILabInTask1/speech-preprocess/save/x64s_8w/checkpoint

#### Optimizer settings
optim:
  name: Adam   ### Adam, RMSprop, SGD
  lr: !!float 5e-4
  momentum: 0
  weight_decay: 0
  clip_norm: 5

#### scheduler settings
scheduler:
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5

#### Resume training settings
resume:
  state: false
  path: /mnt/lustre/sjtu/home/hnz01/code/AILabInTask1/speech-preprocess/save/train2k/checkpoint